### ISSUE TITLE
Broken background update on colorscheme switch at runtime

### ISSUE THREAD

**Issue by RaafatTurki** [sunjon/Shade.nvim#6]
It seems like shade is preventing the background color of some words from changing on cholorscheme switching at runtime (when using `:colorscheme`)

### Actual Behaviour
![actual](https://user-images.githubusercontent.com/16624558/115996842-9b83c800-a5e9-11eb-9e37-b4a9b7b5d72a.gif)

### Expected Behaviour (after removing shade)
![expected](https://user-images.githubusercontent.com/16624558/115996881-b9512d00-a5e9-11eb-87d8-2cf46f27a668.gif)

tested with all variants of both [ayu](https://github.com/ayu-theme/ayu-vim) and [iceberg](https://github.com/cocopon/iceberg.vim) with only shade and the two aforementioned colorscheme plugins using packer.

shade was setup with zero config
```lua
require'shade'.setup()
```

**Comment by sunjon** [comment]
It's captured the background colour and derived is own from it. It'll need a `colorscheme` autocommand to track user changes.
I'll look into it as soon as I have time.

**Comment by sunjon** [comment]
Should be fixed in https://github.com/sunjon/Shade.nvim/commit/0507aa26c0d33f75ed68bc38c1800ffb8d634200 .
Let me know if it worked.

**Comment by RaafatTurki** [comment]
it's still the same, however it's fixed on 1st switch only

**Comment by ryuheechul** [comment]
This issue still seems to be present as @RaafatTurki commented.
First switch works fine but from the second time the issue is still same.

**Comment by Galicarnax** [comment]
Also confirm the issue. With disabled `Shade`, changing colorscheme at runtime has no bugs. With `Shade` enabled, the background is broken after switching the colorscheme.
